services:
  - type: cron
    name: sniper-auto-engine
    schedule: "15 4 * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python sniper_run_all.py"

  - type: web
    name: sniper-p2-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
